name: Sync Service Folder to Main

on:
  push:
    branches:
      - service/**

jobs:
  sync-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Extract service name from branch
        id: extract
        run: echo "SERVICE_NAME=${GITHUB_REF#refs/heads/service/}" >> $GITHUB_ENV

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main_branch

      - name: Copy updated service folder to main branch
        run: |
          SOURCE_PATH=services/${{ env.SERVICE_NAME }}/
          DEST_PATH=main_branch/services/${{ env.SERVICE_NAME }}/

          if [ -d "$SOURCE_PATH" ]; then
            echo "✅ Found source folder: $SOURCE_PATH"
            rm -rf "$DEST_PATH"
            mkdir -p "$DEST_PATH"
            cp -r "$SOURCE_PATH"/. "$DEST_PATH"
          else
            echo "❌ Folder $SOURCE_PATH not found in branch."
            exit 1
          fi

      - name: Commit and push to main
        run: |
          cd main_branch
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add services/${{ env.SERVICE_NAME }}
          git commit -m "Sync ${{ github.ref_name }} → main/services/${{ env.SERVICE_NAME }}" || echo "No changes to commit"
          git push origin main
