apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-dabconfig" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- $files := .Files }}
  {{- range tuple "softwareenv.sh" "code.sh" "data.sh" "setup.sh" "jayzgotdakeys.sh" }}
  {{ . }}: |-
        {{ $files.Get .  | nindent 8  }}
  {{- end }}
